### ISSUE TITLE
Would this be fast enough to handle the debounce for a reed switch flow meter?

### ISSUE THREAD

**Issue by mrarmyant** [evert-arias/EasyButton#15]

**Comment by evert-arias** [comment]
@mrarmyant 
Have not try it with reed switch flow meter but i think it will handle it.

**Comment by evert-arias** [comment]
@mrarmyant
Have not test it with reed switch flow meter but I think it will handle it.

**Comment by evert-arias** [comment]
I'm closing this since it's not an issue.
