### ISSUE TITLE
Compile errors in MultipleButtons.ino

### ISSUE THREAD

**Issue by vazquezjm** [evert-arias/EasyButton#21]
HI @evert-arias !

I'm getting the following error when compiling the example `MultipleButtons.ino`

```
\Arduino\libraries\EasyButton\src\EasyButton.cpp: In member function 'void EasyButton::enableInterrupt(EasyButton::callback_t)':

\Arduino\libraries\EasyButton\src\EasyButton.cpp:174:63: error: cannot convert 'EasyButton::callback_t {aka std::function<void()>}' to 'void (*)()' for argument '2' to 'void attachInterrupt(uint8_t, void (*)(), int)'

  attachInterrupt(digitalPinToInterrupt(_pin), callback, CHANGE);

                                                               ^
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.
```

This happens both in Arduino IDE v1.8.9 and PlatformIO (VSC)

**Comment by elC0mpa** [comment]
@vazquezjm thanks for inform us about this issue. We are working on it, it will be fixed in the Next release, wich will be ready soon

**Comment by evert-arias** [comment]
Hi @vazquezjm 
This issue has been fixed https://github.com/evert-arias/EasyButton/commit/fed0ad89c017bb470ac818d4f93ec8c3a5f84b8a and a new release it's now available to [download](https://github.com/evert-arias/EasyButton/releases/tag/v1.1.1).
https://github.com/evert-arias/EasyButton/releases/tag/v1.1.1

We appreciate you feedback

**Comment by vazquezjm** [comment]
Wow, that was super fast!

Quick note: I added the following line to my project `platformio.ini` in order to start using 1.1.1 as described [here](https://docs.platformio.org/en/latest/userguide/lib/cmd_install.html#description)

```lib_deps = EasyButton@1.1.1```

Although it looks like it is trying to download 1.1.1, I get this message:

![image](https://user-images.githubusercontent.com/5269397/63231164-1e863580-c1ee-11e9-9848-485035545381.png)

Is that a PlatformIO issue?

**Comment by evert-arias** [comment]
@vazquezjm 
PlatformIO takes a few hours even a day to update its libraries registry. 
I suggest you wait a couple of hours until the new version is available on PlatformIO. 
https://platformio.org/lib/show/5741/EasyButton

**Comment by evert-arias** [comment]
This issue has been solved
