### ISSUE TITLE
Does the library EasyButton work well for 365x24h continuous application?

### ISSUE THREAD

**Issue by thkfighter** [evert-arias/EasyButton#26]
Is there any timer variable that will overflow when the application runs for a long time?

**Comment by elC0mpa** [comment]
Why are you asking this @thkfighter? Inside the library we only use the millis() function wich use the timer0 or timer1, I don't remember exactly wich of these is. But the value returned by this function overflows after more than a month.

**Comment by thkfighter** [comment]
> Why are you asking this @thkfighter? Inside the library we only use the millis() function wich use the timer0 or timer1, I don't remember exactly wich of these is. But the value returned by this function overflows after more than a month. If you want to improve your skills about timing events in microcontrollers, check this link: https://github.com/elC0mpa/Arduino-Tutorials/tree/master/Timing%20Events

**Comment by thkfighter** [comment]
> Why are you asking this @thkfighter? Inside the library we only use the millis() function wich use the timer0 or timer1, I don't remember exactly wich of these is. But the value returned by this function overflows after more than a month. If you want to improve your skills about timing events in microcontrollers, check this link: https://github.com/elC0mpa/Arduino-Tutorials/tree/master/Timing%20Events

I wonder if the button will fail when the timer variable overflows.
