### ISSUE TITLE
too complicated documentation

### ISSUE THREAD

**Issue by danidavid** [evert-arias/EasyButton#28]
the problem in understanding occured when reading invert and pullup resistors section.

Should use simple wordings, the wordings are not elaborating the function clearly, also elaborate more in a keep it short simple (KISS) manner. Also should be clear and concise.

**Comment by evert-arias** [comment]
Hello @danidavid 
Thank you very much for showing interest in **EasyButton**. We really appreciate your opinion and the recommendations made on how to improve the library's documentation. The documentation will be improved in the near future, however you can feel free to contribute by doing PR.
