### ISSUE TITLE
v2 branch removal of begin() may be problematic 

### ISSUE THREAD

**Issue by liebman** [evert-arias/EasyButton#29]
Constructors for c++ objects may run before frameworks on platforms like esp8266 and esp32 are fully initialized.  Typically this is why begin() is used.  I noticed this while looking for a solution for INTERRUPT being redefined in the current release on esp32.

**Comment by evert-arias** [comment]
Hi @liebman 
Thanks for pointing this out. In fact, it is a good point, I will consider it for v2. 
Regards

**Comment by evert-arias** [comment]
I consider this issue resolved and therefore I will be closing it. Feel free to open a new issue if you need to.
